name: Get Recent Commit Authors
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Recent Commit Authors
        uses: AidarGatin/github-recent-commits-authors@v1.1
        id: recent-commits
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          days-before: '7' 
          output-format: 'raw' 

      - name: Print Authors' Emails
        run: |
          echo "Authors' Emails: ${{ steps.recent-commits.outputs.emails }}"