name: Get Recent Commit Authors
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Get Recent Commit Authors
        uses: AidarGatin/github-recent-commits-authors@v1.3
        id: recent-commits
        with:
          github_repository: ${{ github.repository }}
          github_token: ${{ secrets.GH_TOKEN }}
          days_before: 7
          output_format: 'raw' 

      - name: Print Authors' Emails
        run: |
          echo "Authors' Emails: ${{ steps.recent-commits.outputs.emails }}"